basePath: /api
definitions:
  model.SignIn:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.SignUp:
    properties:
      email:
        type: string
      password:
        type: string
      repeat_password:
        type: string
    type: object
  model.TokenOut:
    properties:
      token:
        type: string
    type: object
  model.User:
    properties:
      birth_date:
        type: string
      email:
        type: string
      name:
        type: string
    type: object
  response.Error:
    properties:
      error:
        type: string
    type: object
  response.Success:
    properties:
      message:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: helloladies API [go + gin]
  title: helloladies API
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: sign in data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.SignIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TokenOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      summary: SignIn
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: sign up data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.SignUp'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TokenOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      summary: SignUp
      tags:
      - auth
  /logged/users/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - Token: []
      summary: ListUsers
      tags:
      - users
  /logged/users/delete:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - Token: []
      summary: DeleteUser
      tags:
      - users
  /logged/users/get:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - Token: []
      summary: GetUser
      tags:
      - users
  /logged/users/update:
    put:
      consumes:
      - application/json
      parameters:
      - description: user data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - Token: []
      summary: UpdateUser
      tags:
      - users
  /ping:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
      summary: Ping
      tags:
      - api
securityDefinitions:
  Token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
